/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "b1.h"
#include <string.h>
#define MAX_CHAR 500
#define MAX_WORD 15000

char **
contapalavra_1_svc(char **argp, struct svc_req *rqstp)
{
	printf("[LOG]Recebido: %s\n", *argp);

	char **result = malloc(sizeof(char *) * MAX_WORD);
	*result = "";
	char *aux = *argp;

	char *palavra = malloc(sizeof(char) * MAX_CHAR);
	int qtdPalavras = 0;
	palavras *contador = malloc(sizeof(palavras) * MAX_WORD);

	for (int i = 0; i < MAX_CHAR; i++)
	{
		contador[i].palavra = malloc(sizeof(char *) * MAX_CHAR);
		contador[0].qtd = 0;
	}

	for (int i = 0, j = 0, k = 0; i < strlen(aux); i++)
	{
		for (j = 0; aux[i] != ' '; i++, j++)
		{
			palavra[j] = aux[i];
			if (aux[i + 1] == ' ')
			{
				palavra[j + 1] = '\0';
				if (qtdPalavras == 0)
				{
					strcpy(contador[0].palavra, palavra);
					contador[0].qtd = 1;
					qtdPalavras++;
				}
				else
				{
					for (k = 0; k < qtdPalavras; k++)
					{
						if (!strcmp(palavra, contador[k].palavra))
						{
							contador[k].qtd++;
							break;
						}
					}
					if (k == qtdPalavras)
					{
						strcpy(contador[k].palavra, palavra);
						contador[k].qtd = 1;
						qtdPalavras++;
					}
				}
			}
		}
	}

	free(palavra);

	char *str = malloc(sizeof(char) * MAX_WORD);
	char *str2 = malloc(sizeof(char) * MAX_WORD);

	strcpy(str2, "|--Palavra--|--Quantidade--|\n");
	for (int i = 0; i < qtdPalavras; i++)
	{
		sprintf(str, "%s\t\t%d\n", contador[i].palavra, contador[i].qtd);
		strcat(str2, str);
	}
	printf("\n");

	sprintf(str, "-----------------------------\n", qtdPalavras);
	strcat(str2, str);
	sprintf(str, "Quantidade de palavras: %d\n", qtdPalavras);
	strcat(str2, str);

	free(str);

	*result = str2;

	return result;
}
